#!/bin/bash

# http://wiki.openttdcoop.org/Basecosts
# http://wiki.ttdpatch.net/tiki-index.php?page=BaseCosts
# NewBaseCost = OldBaseCost * 2^(n-8), where n is the value of property 08.

GRFID="4D 47 03 C1"
FILENAME="basecosts-presets"

. lib/hg.version.sh

NFO="sprites/$FILENAME.nfo"
[ ! -d "sprites" ] && mkdir sprites

GOTOEND="0 * 0 09 9A 01 \71 \b1 00"

cat >$NFO <<EOF
// Automatically generated by GRFCODEC. Do not modify!
// (Info version 7)
// Format: spritenum pcxfile xpos ypos compression ysize xsize xrel yrel
  0 * 4 00 00 00 00

 -1 * 0  14 "C" "INFO"
                  "B" "PALS" \w1 "A"
                  "B" "VRSN" \w4 \d$REVISION
                  "B" "NPAR" \w1 \b1
                  "C" "PARA"
                      "C" \d0
                          "T" "NAME" 7F "BaseCosts Set" 00
                          "T" "DESC" 7F "Chose one of the presets:" 0D
                            "BaseCosts hard (default) - Luukland hard/easy - Cadde hard" 00
                          "B" "TYPE" \w1 \b0
                          "B" "LIMI" \w8 \d1 \d4
                          "C" "VALU"
                              "T" \d1 7F "BaseCosts hard (default)" 00
                              "T" \d2 7F "Luukland hard" 00
                              "T" \d3 7F "Luukland easy" 00
                              "T" \d4 7F "Cadde hard" 00
                              00
                          00
                      00
                  00
            00

  0 * 0	08 07 $GRFID "BaseCosts Mod Presets $VERSION" 00
    "http://wiki.openttdcoop.org/BaseCosts" 0D
    "Presets (Parameter):" 0D
    "default BaseCosts hard = 1" 0D
    "Luukland hard = 2 / easy = 3" 0D
    "Cadde hard = 4" 0D
    "$VERDATE / GPL / Ammler" 00

// first pair params:
  0 * 0 0D // ActionD <target> <operation> <source1> <source2> [<data>]
    00          // Parameter 0
    80          // if target not set, target = source1 
    FF          // source1: use value from data
    00          // source2: ignored
    \d1         // data

// if param0 > 1
  0 * 0 09 // Action[07/09] <variable> <varsize> <condition-type> <value> <num-sprites>
    00          // Parameter 0
    01          // size
    \7>         // condition: equal to
    \b1
    02          // skip next 2

  0 * 0 00 // Action0 <Feature> <Num-props> <Num-info> <Id> (<Property <New-info>)...
    08          // Properties for general variables
    01 \b60
    00          // ID (param0)
    08          // Basecosts

\b8
\b8
\b8
\b9
\b10
\b9
\b9
\b9
\b12
\b9
\b9
\b12
\b9
\b9
\b9
\b9
\b9
\b10
\b9
\b9
\b9
\b12
\b9
\b9
\b9
\b10
\b9
\b8
\b8
\b8
\b8
\b8
\b8
\b8
\b9
\b8
\b8
\b8
\b8
\b8
\b8
\b8
\b9
\b9
\b9
\b11
\b9
\b8
\b10
\b8
\b9
\b8
\b9
\b8
\b9
\b8
\b9
\b10
\b9
\b10

$GOTOEND

// if parameter 0 > 2
// Luukland hard
  0 * 0 09 // Action[07/09] <variable> <varsize> <condition-type> <value> <num-sprites>
    00          // Parameter 0
    01          // size
    \7>         // condition: equal to
    \b2
    02          // skip next 2

  0 * 0 00 // Action0 <Feature> <Num-props> <Num-info> <Id> (<Property <New-info>)...
    08          // Properties for general variables
    01 \b60
    00          // ID (param0)
    08          // Basecosts

\b8
\b8
\b6
\b8
\b9
\b8
\b6
\b8
\b9
\b8
\b8
\b11
\b8
\b8
\b8
\b8
\b8
\b8
\b7
\b8
\b8
\b9
\b8
\b8
\b8
\b8
\b8
\b8
\b0
\b0
\b0
\b0
\b0
\b0
\b8
\b0
\b0
\b0
\b0
\b0
\b11
\b0
\b11
\b11
\b11
\b11
\b8
\b8
\b8
\b8
\b8
\b8
\b8
\b8
\b8
\b8
\b8
\b8
\b7
\b8


$GOTOEND

// if parameter 0 > 3
// Luukland easy
  0 * 0 09 // Action[07/09] <variable> <varsize> <condition-type> <value> <num-sprites>
    00          // Parameter 0
    01          // size
    \7>         // condition: equal to
    \b3
    02        // skip next 2

  0 * 0 00 // Action0 <Feature> <Num-props> <Num-info> <Id> (<Property <New-info>)...
    08          // Properties for general variables
    01 \b60
    00          // ID (param0)
    08          // Basecosts
\b8
\b8
\b6
\b8
\b9
\b8
\b6
\b8
\b9
\b8
\b8
\b11
\b8
\b8
\b8
\b8
\b8
\b8
\b7
\b8
\b8
\b9
\b8
\b8
\b8
\b8
\b8
\b8
\b0
\b0
\b0
\b0
\b0
\b0
\b8
\b0
\b0
\b0
\b0
\b0
\b11
\b0
\b9
\b9
\b9
\b11
\b8
\b8
\b8
\b8
\b8
\b8
\b8
\b8
\b8
\b8
\b8
\b8
\b7
\b8

$GOTOEND

// if parameter 0 > 4
// Cadde hard
  0 * 0 09 // Action[07/09] <variable> <varsize> <condition-type> <value> <num-sprites>
    00          // Parameter 0
    01          // size
    \7>         // condition: equal to
    \b4
    02        // skip next 2

  0 * 0 00 // Action0 <Feature> <Num-props> <Num-info> <Id> (<Property <New-info>)...
    08          // Properties for general variables
    01 \b60
    00          // ID (param0)
    08          // Basecosts
\b8
\b9
\b9
\b10
\b10
\b9
\b9
\b9
\b10
\b9
\b9
\b13
\b9
\b9
\b9
\b9
\b9
\b10
\b9
\b10
\b11
\b10
\b8
\b8
\b8
\b8
\b9
\b8
\b8
\b9
\b9
\b9
\b9
\b8
\b9
\b9
\b12
\b9
\b9
\b9
\b9
\b8
\b9
\b9
\b9
\b10
\b9
\b9
\b9
\b9
\b8
\b8
\b8
\b8
\b8
\b8
\b9
\b8
\b9
\b9

$GOTOEND
EOF

. lib/buildgrf.sh

exit

